apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-nginx-dev
  template:
    metadata:
      labels:
        app: hello-nginx-dev
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
