apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-nginx-prod
  template:
    metadata:
      labels:
        app: hello-nginx-prod
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
